### PR TITLE
Implemented swipe gesture to open panel, updated icons

### PR DESCRIPTION
**Pull request by 0xBADEAFFE**
Allows better navigation on mobile devices.

### CODE REVIEW

**Comment by rmeissn** [comment]
Hi Vincent,

thank you for your commitment to the HTWK-App codebase. I really like your Icons and Splashscreens!
I've commented some of your commits, because I think they can be optimized in certain areas. Feel free to have a conversation inside the comment section of these commits or by email, if you want to ask me some general stuff.

**Comment by vincent-t** [comment]
I'll try to revert some of my changes tomorrow. The swipe gestures working well on firefox... I don't understand why they are not working on Android. You are right about the menu color, i will try some other colors, to achieve a unified material design look. But I still like to use this pallet:
color

The header bar should be bigger to match other apps. It is too small on a nexus5:
screenshot_20150922-233133
screenshot_20150922-233202

**Comment by rmeissn** [comment]
Sounds great! =)

A while back I've found this WebApp to generate colour schemes that match out of the box: [Coolers](https://coolors.co/). With your colors, I like this one: [Color Scheme Example](https://coolors.co/app/2196f3-0267c1-efa00b-d65108-591f0a) (as one example).

Well, you're right with the headerbar size. Feel free to experiment, but remember to also test the size inside chrome and firefox on a desktop computer. BTW: I am developing with Googles Chrome browser and (unfortunately) I hadn't the time to test everything on firefox (like animations).

I will test your swipe implementation after my holidays. Nevertheless, your actual implementation breaks swipe in timetable and canteen view inside chrome.
I think that a pruned version of chromes HTML, CSS and JS engine is used inside Android to render webviews (our app). Unfortunately, before we removed swipe, it was working on desktop chrome, but not on the Android App.

**Comment by vincent-t** [comment]
I reverted some changes. I also tested the swipe implementation on mobile chrome and it works well. Only problem is double swipe in timetable and canteen view. (https://rawgit.com/vincent-t/Smartphone-App/master/www/index.html)

**Comment by vincent-t** [comment]
Edge swipe works well on chrome mobile, also works without interfering swipe in timetable and canteen view (https://rawgit.com/vincent-t/Smartphone-App/master/www/index.html).

**Comment by vincent-t** [comment]
@rmeissn I implemented 30px barriers on y-axis, like you suggested. (https://rawgit.com/vincent-t/Smartphone-App/master/www/index.html)

**Pull request merged**
